---
title: "Spain"
description: |
  A simple analysis on the COVID-19 situation in Spain.
author:
  - name: Xueqi Goh
    url: https://example.com/norajones
date: 09-02-2021
output:
  distill::distill_article:
    self_contained: false
---



```{r}
library(dplyr)
library(tidyverse)
library(ggplot2)
library(readr)
library(gt)
library(lubridate)
```

# Data Description

explain na


```{r data, echo=FALSE, message=FALSE}
data <- read_csv("/Users/fairystephanie/Desktop/ETC5523/Blog1/blog-xgoh0002/data/owid-covid-data.csv")
```

```{r dataa, message=FALSE}
covid <- read_csv("/Users/fairystephanie/Desktop/ETC5523/Blog1/blog-xgoh0002/data/coronavirus.csv")

```

```{r vaccine, message = FALSE}
vaccine <- read_csv("/Users/fairystephanie/Desktop/ETC5523/Blog1/blog-xgoh0002/data/covid19_vaccine.csv")
```

```{r spain, echo=FALSE}
spain <- data %>%
  filter(location == "Spain") %>%
  select(date, total_cases, new_cases, total_deaths, new_deaths, icu_patients) 
  spain[is.na(spain)] = 0
```


```{r Table1, echo=FALSE}
DT::datatable(spain, class = 'cell-border stripe', colnames = c('Date', 'Total Cases', 'New Cases', 'Total Deaths', 'New Deaths', 'ICU patients'), caption = 'Covid-19 Situation in Spain from Feb 2020 to Sep 2021', filter = 'top', options = list( pageLength = 10)) 
```

```{r}
vaccine <- vaccine
myDate = as.POSIXct(vaccine$date)  
month <- format(myDate,"%m")
mymonths <- c("Jan","Feb","Mar",
              "Apr","May","Jun",
              "Jul","Aug","Sep",
              "Oct","Nov","Dec")
vaccine <- vaccine %>%
  add_column(newColname = myDate) %>%
  mutate(Month = month(newColname)) 
vaccine$Month <- mymonths[ vaccine$Month]


```


```{r}
spain2 <- vaccine %>%
  filter(country_region == "Spain") %>%
  select(Month, doses_admin, people_partially_vaccinated, people_fully_vaccinated) %>%
  dplyr::group_by(Month) %>%
  summarise(doses_admin = sum(doses_admin),
            people_partially_vaccinated = sum(people_partially_vaccinated),
            people_fully_vaccinated= sum(people_fully_vaccinated)) %>%
  arrange(-doses_admin)

```


```{r}
gt(spain2) %>%
  tab_header(title = "COVID-19 Vaccination Status in Spain from Jan 2021 to Aug 2021",
             subtitle = "Arranged by Sum of Total Vaccine Administered (High to Low)") %>%
  tab_source_note(md("xxx")) %>%
  cols_label(
    Month = html("Month"),
    doses_admin = html('Total Vaccine Administered'),
    people_partially_vaccinated = html('People Partially Vaccinated'),
    people_fully_vaccinated = html('People Fully Vaccinated')
  )
```



Distill is a publication format for scientific and technical writing, native to the web.

Learn more about using Distill at <https://rstudio.github.io/distill>.

#Reference
Hasell, J., Mathieu, E., Beltekian, D. et al. A cross-country database of COVID-19 testing. Sci Data 7, 345 (2020)

